logging:
  level:
    ROOT: DEBUG
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/animals?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 'Maasai2Mara'
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true